/**
 * LICENSE_PLACEHOLDER
 **/
import { FixedTable } from '@regardsoss/components'
import CatalogEntitySelector from '../../models/catalog/CatalogEntitySelector'
import CatalogEntityActions from '../../models/catalog/CatalogEntityActions'
import ResulsTypeButtons from './ResultsTypeButtons'

/**
 * React container to manage search requests and display results.
 * Search queries are generated by the FormComponent and used by this container.
 * @author Sébastien binda
 */
class SearchResultsComponent extends React.Component {

  static propTypes = {
    searchQuery: React.PropTypes.string,
  }

  render() {
    return (
      <div>
        <ResulsTypeButtons />
        <div style={{ marginRight: 40 }}>
          <FixedTable
            PageActions={CatalogEntityActions}
            PageSelector={CatalogEntitySelector}
            pageSize={15}
            lineHeight={35}
            requestParams={{ queryParams: this.props.searchQuery }}
          />
        </div>
      </div>
    )
  }
}

export default SearchResultsComponent
