image: node:7.10.1-wheezy

stages:
  - test

test:
  stage: test
  script:
   - echo $0
   - echo $? && echo "This is a second command"
   - cd frontend-webapp/src/main/webapp/
   - npm config set proxy "http://proxy2.si.c-s.fr:3128/"
   - npm run bootstrap
   - npm install
   - npm run build:dll
   - ls -al webpack-config-front
   - npm run build:plugins