
const METADATA_ACCESS_ENUM = {
  DATASET_AND_OBJECT_ACCESS: 'FULL_ACCESS',
  DATASET_ACCESS: 'RESTRICTED_ACCESS',
  NO_ACCESS: 'NO_ACCESS',
}

const DATA_ACCESS_ENUM = {
  AUTHORIZED: 'INHERITED_ACCESS',
  REFUSED: 'NO_ACCESS',
  AUTHORIZED_BY_PLUGIN: 'CUSTOM_ACCESS',
}

const QUALITY_LEVEL_ENUM = {
  ACCEPTED: 'ACCEPTED',
  ACCEPTED_WITH_WARNINGS: 'ACCEPTED_WITH_WARNINGS',
  REJECTED: 'REJECTED',
}

export default {
  QUALITY_LEVEL_ENUM,
  METADATA_ACCESS_ENUM,
  DATA_ACCESS_ENUM,
}
